Repository mikejseay/exquisite-text, pull requests merged in 2022-08, with the labels that each got.

#41 feat: macOS command key pass turn
  src/components/LineInput/index.tsx
Labels: enhancement

#42 fix: settings cannot be deselected
  src/components/GameSettings/index.tsx
Labels: bug

#43 feat: use game settings defined in lobby
  server/poem.ts
  server/poemOld.ts
  src/components/App/index.tsx
  src/components/GameSettings/index.tsx
  src/components/LineInput/index.tsx
  src/components/LineInput/index.tsx.bk
  src/types/index.ts
Labels: enhancement

#44 feat: basic spectator view
  server/poem.ts
  src/components/LineInput/index.tsx
  src/components/Lines/index.tsx
  src/components/Lines/styles.ts
  src/routes/spectate.tsx
  src/types/index.ts
Labels: enhancement

#45 Full stack cleanup
  server/entity/poem.ts
  server/poem.ts
  server/queries.ts
  server/routes/index.ts
  server/routes/users.ts
  server/start.ts
  src/components/App/index.tsx
  src/components/App/styles.ts
  src/components/GameSettings/index.tsx
  src/components/GameSnack/index.tsx
  src/components/GameState/index.tsx
  src/components/GameState/styles.ts
  src/components/GameTransition/index.tsx
  src/components/LineInput/LineInput.css
  src/components/LineInput/index.tsx
  src/components/Lines/index.tsx
  src/components/Menu/index.tsx
  src/components/Poems/index.tsx
  src/components/Tutorial/index.tsx
  src/components/UserTable/index.tsx
  src/helpers/index.ts
  src/index.tsx
  src/routes/game.tsx
  src/routes/host.tsx
  src/routes/lobby.tsx
  src/screens/Game/index.tsx
  src/screens/Game/styles.ts
  src/screens/Host/index.tsx
  src/screens/Join/index.tsx
  src/screens/Lobby/index.tsx
  src/screens/Spectate/index.tsx
Labels: enhancement

#46 feat: basic implementation of device recognition
  server/poem.ts
  src/components/App/index.tsx
  src/index.tsx
  src/screens/Disconnected/index.tsx
  src/screens/Game/index.tsx
  src/screens/Join/index.tsx
  src/screens/Spectate/index.tsx
  src/types/index.ts
Labels: enhancement

#47 chore: future-proof react imports
  src/components/App/App.test.tsx
  src/components/App/index.tsx
  src/components/App/styles.ts
  src/components/GameSettings/index.tsx
  src/components/GameSnack/index.tsx
  src/components/GameState/index.tsx
  src/components/GameState/styles.ts
  src/components/GameTransition/index.tsx
  src/components/LineInput/index.tsx
  src/components/LineInput/styles.ts
  src/components/Lines/index.tsx
  src/components/Menu/index.tsx
  src/components/Poems/index.tsx
  src/components/Poems/styles.ts
  src/components/Tutorial/index.tsx
  src/components/Tutorial/styles.ts
  src/components/UserTable/index.tsx
  src/screens/Disconnected/index.tsx
  src/screens/Game/styles.ts
Labels: bug

#48 fix: improve array readability
  src/components/App/index.tsx
  src/components/GameSettings/index.tsx
  src/components/GameSnack/index.tsx
  src/components/GameState/index.tsx
  src/components/LineInput/index.tsx
  src/components/Lines/index.tsx
  src/components/Menu/index.tsx
  src/components/Poems/index.tsx
  src/components/Tutorial/index.tsx
  src/components/UserTable/index.tsx
  src/screens/Join/index.tsx
Labels: enhancement

#49 chore: provide .env example and update README
  .env.example
  README.md
  server/.env.example
Labels: documentation

#51 fix: indentation 4 spaces, double quotes
  .eslintrc.js
  .prettierrc
  package.json
  server/app.ts
  server/entity/poem.ts
  server/package.json
  server/poem.ts
  server/public/index.html
  server/public/stylesheets/style.css
  server/queries.ts
  server/routes/index.ts
  server/routes/users.ts
  server/socketFunctionality.ts
  server/start.ts
  server/tsconfig.json
  server/yarn.lock
  src/components/App/App.test.tsx
  src/components/App/index.tsx
  src/components/App/styles.ts
  src/components/GameSettings/index.tsx
  src/components/GameSnack/index.tsx
  src/components/GameState/index.tsx
  src/components/GameTransition/index.tsx
  src/components/LineInput/index.tsx
  src/components/LineInput/styles.ts
  src/components/Lines/index.tsx
  src/components/Menu/index.tsx
  src/components/Poems/index.tsx
  src/components/Poems/styles.ts
  src/components/Settings/index.tsx
  src/components/Tutorial/index.tsx
  src/components/Tutorial/styles.ts
  src/components/UserTable/index.tsx
  src/helpers/index.ts
  src/index.css
  src/index.tsx
  src/reportWebVitals.ts
  src/screens/Disconnected/index.tsx
  src/screens/Game/index.tsx
  src/screens/Game/styles.ts
  src/screens/Host/index.tsx
  src/screens/Join/index.tsx
  src/screens/Lobby/index.tsx
  src/screens/Spectate/index.tsx
  src/setupTests.ts
  src/types/index.ts
  yarn.lock
Labels: enhancement

#53 fix: imports in app.ts, rename sockets
  server/app.ts
  server/package.json
  server/routes/index.ts
  server/routes/users.ts
  server/sockets.ts
  server/start.ts
  server/yarn.lock
  src/components/Tutorial/index.tsx
  src/screens/Game/index.tsx
Labels: bug

#54 feat: join ongoing game as spectator
  server/sockets.ts
  src/components/App/index.tsx
Labels: enhancement

#55 fix: ensure behavior OK after close tab and use hotkey
  server/sockets.ts
  src/components/LineInput/index.tsx
Labels: bug, enhancement

#56 feat: eslint sort-keys
  .eslintrc.js
Labels: enhancement

#57 fix: eslint short-keys config & alphabetize keys
  .eslintrc.js
  package.json
  src/components/GameState/index.tsx
  src/components/LineInput/index.tsx
  src/components/LineInput/styles.ts
  src/components/Lines/index.tsx
  src/helpers/index.ts
  src/screens/Game/styles.ts
  src/screens/Join/index.tsx
  yarn.lock
Labels: bug

#58 feat: basic leave game functionality
  server/entity/poem.ts
  server/queries.ts
  server/sockets.ts
  server/start.ts
  src/components/GameSnack/index.tsx
  src/components/Leave/index.tsx
  src/components/LineInput/index.tsx
  src/components/LineInput/styles.ts
  src/components/Settings/index.tsx
  src/screens/Game/index.tsx
  src/types/index.ts
Labels: enhancement

#59 fix: mobile tutorial modal
  src/components/Tutorial/index.tsx
  src/components/Tutorial/styles.ts
Labels: bug

#60 feat: initial dark mode
  src/index.css
Labels: enhancement

#61 feat: dark mode highlight color teal
  src/index.css
Labels: enhancement

#63 Leaving and afk improvements
  server/sockets.ts
  src/components/CreateGame/index.tsx
  src/components/Leave/index.tsx
  src/components/LineInput/index.tsx
  src/components/Tutorial/index.tsx
Labels: enhancement

#64 Some user friendliness stuff
  src/components/LineInput/index.tsx
  src/components/Tutorial/index.tsx
  src/components/Tutorial/styles.ts
Labels: bug, enhancement

#65 feat: intial store and viz lines
  server/entity/line.ts
  server/queries.ts
  server/sockets.ts
  src/components/LineInput/styles.ts
  src/components/Lines/index.tsx
  src/components/PoemLines/index.tsx
  src/components/PoemLines/styles.ts
  src/components/Poems/index.tsx
  src/components/PoemsLines/index.tsx
  src/components/PoemsLines/styles.ts
  src/screens/Game/index.tsx
  src/types/index.ts
Labels: enhancement

#66 feat: copy poem to clipboard
  package.json
  src/components/Poem/index.tsx
  src/components/Poem/styles.ts
  src/components/Poems/index.tsx
  src/components/Poems/styles.ts
  yarn.lock
Labels: enhancement

#67 feat: copy button on poemslines
  src/components/PoemsLines/index.tsx
Labels: enhancement

#69 chore: constants file, refactoring, cleanup
  .eslintrc.js
  server/queries.ts
  server/sockets.ts
  src/components/App/index.tsx
  src/components/App/styles.ts
  src/components/CreateGame/index.tsx
  src/components/CreateGame/styles.ts
  src/components/GameSnack/index.tsx
  src/components/GameState/index.tsx
  src/components/GameState/styles.ts
  src/components/GameTransition/index.tsx
  src/components/Leave/index.tsx
  src/components/Leave/styles.ts
  src/components/LineInput/index.tsx
  src/components/LineInput/styles.ts
  src/components/Lines/index.tsx
  src/components/Lines/styles.ts
  src/components/Poem/index.tsx
  src/components/PoemLines/index.tsx
  src/components/PoemsLines/index.tsx
  src/components/Settings/index.tsx
  src/components/Tutorial/index.tsx
  src/components/Tutorial/styles.ts
  src/components/UserTable/index.tsx
  src/constants/index.ts
  src/helpers/index.ts
  src/screens/Disconnected/index.tsx
  src/screens/Game/index.tsx
  src/screens/Game/styles.ts
  src/screens/Host/index.tsx
  src/screens/Join/index.tsx
  src/types/index.ts
Labels: bug, enhancement

#70 chore: room self-destruct, refactor, server constants
  .eslintrc.js
  server/package.json
  server/queries.ts
  server/sockets.ts
  src/components/App/index.tsx
  src/components/GameSettings/index.tsx
  src/components/Leave/index.tsx
  src/components/LineInput/index.tsx
  src/components/PoemsLines/index.tsx
  src/constants/index.ts
  src/index.tsx
  src/screens/Join/index.tsx
  src/types/index.ts
Labels: bug, enhancement
