Repository mikejseay/exquisite-text, pull requests merged in 2022-07, with the labels that each got.

#2 chore: upgrade nodejs, use yarn
  package-lock.json
  package.json
  src/server/yarn.lock
  yarn.lock
Labels: bug

#3 chore: add github actions for project assignment
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/github-actions.yaml
Labels: enhancement

#4 chore: reorganize file structure
  .gitignore
  Procfile
  assets/audio/mixkit-message-pop-alert-2354.mp3
  assets/images/logo.svg
  server/app.js
  server/package.json
  server/poem.js
  server/public/index.html
  server/public/stylesheets/style.css
  server/queries.js
  server/routes/index.js
  server/routes/users.js
  server/start.js
  server/yarn.lock
  src/components/App/App.css
  src/components/App/App.test.js
  src/components/App/index.js
  src/components/GameState/GameState.css
  src/components/GameState/index.js
  src/components/LineInput/LineInput.css
  src/components/LineInput/index.js
  src/components/Lines/Lines.css
  src/components/Lines/index.js
  src/components/Poems/Poems.css
  src/components/Poems/index.js
  src/components/Settings/Settings.css
  src/components/Settings/index.js
  src/components/Tutorial/Tutorial.css
  src/components/Tutorial/index.js
  src/index.js
Labels: enhancement

#5 fix: revert production and maximum editors change
  server/poem.js
  src/components/App/index.js
Labels: bug

#6 chore: organize client folder
  .prettierrc
  package.json
  src/assets/audio/mixkit-message-pop-alert-2354.mp3
  src/assets/images/logo.svg
  src/components/App/index.js
  src/components/GameState/index.js
  src/components/LineInput/index.js
  src/components/Lines/index.js
  src/components/Poems/index.js
  src/components/Settings/index.js
  src/components/Tutorial/index.js
  src/components/index.js
  src/index.js
  yarn.lock
Labels: enhancement

#7 chore: initial typescript
  package.json
  src/components/App/App.test.tsx
  src/components/App/index.tsx
  src/components/GameState/index.js
  src/components/Lines/index.js
  src/index.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/setupTests.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#8 chore: convert gamestate component to typescript
  src/components/GameState/index.tsx
Labels: enhancement

#10 fix: text area ref typings
  package.json
  src/components/LineInput/index.tsx
  yarn.lock
Labels: bug

#11 feat: add userinfo and role typings
  src/components/App/index.tsx
  src/components/LineInput/index.tsx
  src/types/index.ts
Labels: enhancement

#12 feat: add lines typings
  src/components/GameState/index.tsx
  src/components/LineInput/index.tsx
  src/components/Lines/index.tsx
  src/types/index.ts
Labels: enhancement

#15 chore: typings for poems.js
  package.json
  server/package.json
  server/poem.ts
  server/start.ts
  server/yarn.lock
  src/components/App/index.tsx
  src/types/index.ts
  yarn.lock
Labels: enhancement

#17 feat: convert routes to typescript
  server/app.ts
  server/package.json
  server/routes/index.js
  server/routes/index.ts
  server/routes/users.js
  server/routes/users.ts
Labels: enhancement

#18 chore: add types to queries
  server/package.json
  server/poem.ts
  server/queries.js
  server/queries.ts
  server/tsconfig.json
  src/components/Lines/index.tsx
  src/components/Poems/index.tsx
  src/types/index.ts
Labels: enhancement

#19 chore: convert remaining to typescript, css to types
  src/components/App/App.css
  src/components/App/index.tsx
  src/components/App/styles.ts
  src/components/GameState/GameState.css
  src/components/GameState/index.tsx
  src/components/GameState/styles.ts
  src/components/LineInput/LineInput.css
  src/components/LineInput/index.tsx
  src/components/LineInput/styles.ts
  src/components/Lines/Lines.css
  src/components/Lines/index.tsx
  src/components/Lines/styles.ts
  src/components/Poems/Poems.css
  src/components/Poems/index.tsx
  src/components/Poems/styles.ts
  src/components/Settings/Settings.css
  src/components/Settings/index.tsx
  src/components/Tutorial/Tutorial.css
  src/components/Tutorial/index.tsx
  src/components/Tutorial/styles.ts
Labels: enhancement

#21 fix: use ts-node heroku
  Procfile
Labels: bug

#22 feat: check if isproduction on front end
  src/components/App/index.tsx
Labels: enhancement

#23 fix: use isdevelopment on front end
  src/components/App/index.tsx
Labels: bug

#24 fix: procfile uses start.ts
  Procfile
Labels: bug

#25 fix: procfile transpile only flag
  Procfile
Labels: bug

#26 fix: add cd server to procfile
  Procfile
Labels: bug

#27 fix: add ts-node to front end for heroku
  Procfile
  package.json
  yarn.lock
Labels: bug

#28 fix: attempt heroku fix related to view engine
  README.md
  server/routes/index.ts
  server/routes/users.ts
  src/components/Poems/index.tsx
  src/components/Poems/styles.ts
Labels: bug

#29 fix: debugging heroku build
  server/app.ts
  server/routes/index.ts
  src/components/App/index.tsx
Labels: bug

#30 feat/fix: improve style and behavior of line input
  src/components/App/index.tsx
  src/components/LineInput/index.tsx
  src/components/LineInput/styles.ts
Labels: enhancement

#31 feat: active lineInput has underline indicating suggested input
  src/components/LineInput/index.tsx
  src/components/LineInput/styles.ts
Labels: enhancement

#32 fix: begin refactoring lines, fix spectator view
  src/components/App/index.tsx
  src/components/LineInput/index.tsx
  src/components/LineInput/styles.ts
  src/components/Lines/index.tsx
  src/components/Lines/styles.ts
Labels: bug, enhancement

#33 feat: improve tutorial modal with text and an example GIF
  src/assets/images/exquisiteExample.gif
  src/components/LineInput/index.tsx
  src/components/LineInput/styles.ts
  src/components/Tutorial/index.tsx
  src/components/Tutorial/styles.ts
Labels: enhancement

#34 feat: tutorial modal only auto-shows on first visit
  src/components/Tutorial/index.tsx
Labels: enhancement

#35 feat: initial sequelize setup
  server/entity/poem.ts
  server/package.json
  server/poem.ts
  server/queries.ts
  server/yarn.lock
  src/components/LineInput/index.tsx
  src/components/Lines/index.tsx
  src/components/Poems/index.tsx
  src/types/index.ts
Labels: enhancement

#36 fix: refactor and slim socket communications, clean up unused code
  server/poem.ts
  server/tsconfig.json
  src/components/App/index.tsx
  src/components/GameState/index.tsx
  src/components/LineInput/index.tsx
  src/components/Lines/index.tsx
  src/components/Lines/styles.ts
  src/index.tsx
  tsconfig.json
Labels: bug

#37 feat: Menu button opens left-anchored drawer
  server/poem.ts
  src/components/App/index.tsx
  src/components/Menu/index.tsx
  src/components/Settings/index.tsx
  src/components/Tutorial/index.tsx
  src/index.tsx
Labels: enhancement

#38 Host join routes
  src/components/App/index.tsx
  src/components/Menu/index.tsx
  src/index.tsx
  src/routes/host.tsx
  src/routes/join.tsx
Labels: enhancement
